// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgfrznsvdqwfbmsbsiiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnZnJ6bnN2ZHF3ZmJtc2JzaWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDc0MDQsImV4cCI6MjA1NzE4MzQwNH0.bpGEf0ZaYPYynPQVhtIVpvqgIoOhgxziLxFeV3O814c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);